version: '3.8'

services:
    monoclient:
        container_name: monoclient
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - '8080:8080'
        environment:
            - NODE_ENV=production
        volumes:
            - ./logs:/app/logs
